### ISSUE TITLE
Frame overhead

### ISSUE THREAD

**Issue by annevk** [mcmanus/draft-h2ws#1]
In https://github.com/w3c/ServiceWorker/issues/947#issuecomment-270605411 I had a discussion with @ricea and others about the merits of the WebSocket protocol in an H2 world. It seems that while this proposal tackles the single connection, it still leaves the frames (and therefore the messages) to be rather large.

Perhaps this is not a concern though as the motivation seems primarily to remove the need for servers to keep H1 code around, while being able to retain (legacy) WebSocket deployments.

**Comment by mcmanus** [comment]
You're right about the scope - this is just meant to be a shim rather than a rethinking. hopefully https://github.com/mcmanus/draft-h2ws/blob/master/README.md catches some of that.
